# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  scaleup.core.api:
    build:
      context: "D:\\Workspace\\scaleup-core\\src"
      dockerfile: "ScaleUp.Core.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "scaleup-api:dev"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "C:\\Users\\infer\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\Workspace\\scaleup-core\\src\\ScaleUp.Core.Api:/app:rw"
    - "D:\\Workspace\\scaleup-core\\src:/src:rw"
    - "C:\\Users\\infer\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1.2\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.1.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\infer\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_5_27_14_56_21:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  scaleup.core.backgroundjobs:
    build:
      context: "D:\\Workspace\\scaleup-core\\src"
      dockerfile: "ScaleUp.Core.BackgroundJobs/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "scaleup-backgroundjobs:dev"
    ports:
    - "127.0.0.1:57001:57100"
    - "127.0.0.1:57201:57300"
    volumes:
    - "C:\\Users\\infer\\.nuget\\packages:/root/.nuget/packages"
    - "D:\\Workspace\\scaleup-core\\src\\ScaleUp.Core.BackgroundJobs:/app:rw"
    - "D:\\Workspace\\scaleup-core\\src:/src:rw"
    - "C:\\Users\\infer\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1.2\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.1.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\infer\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_5_27_14_56_21:/var/opt/rider-debugger:rw"
    working_dir: "/app"
