version: '3.4'

services:
  scaleup.core.api:
    image: ${DOCKER_REGISTRY-}scaleup-api
    container_name: scaleup
    build:
      context: .
      dockerfile: ScaleUp.Core.Api/Dockerfile
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080